
CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL NOT NULL PRIMARY KEY, 
	firstname VARCHAR(1000) NOT NULL,
	lastname VARCHAR(1000) NOT NULL, 
	username VARCHAR(1000) NOT NULL,
	image TEXT DEFAULT 'none',
	age INT NOT NULL,
	gender VARCHAR(1000) NOT NULL,
	gender_interest VARCHAR(1000) DEFAULT 'Everyone',
	bio VARCHAR(1000) DEFAULT 'none',
	tags VARCHAR(1000),
	city VARCHAR(1000),
	country VARCHAR(1000),
	actual_location VARCHAR(1000), /* complete this */
	password VARCHAR(1000) NOT NULL,
	email VARCHAR(1000), 
	active SMALLINT DEFAULT 0,
	token varchar(255) NOT NULL DEFAULT 0,
	fame INT NOT NULL DEFAULT 0,
	online SMALLINT DEFAULT 0,
	last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_images (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	user_id INT NOT NULL, 
	image TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS matches (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	user1 INT NOT NULL,
	user2 INT NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	liker_id INT NOT NULL,
	liked_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	sender_id INT NOT NULL, 
	receiver_id INT NOT NULL,
	message TEXT NOT NULL,
	read SMALLINT DEFAULT 0,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	sender_id INT NOT NULL, 
	reciever_id INT NOT NULL,
	text VARCHAR(100),
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocks (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	user_id INT NOT NULL,
	blocked_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS reports (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	reporter_id INT NOT NULL,
	reported_id INT NOT NULL
);